[build]
builder = "NIXPACKS"
buildCommand = "cd ../.. && pnpm install && pnpm build --filter=api"

[deploy]
startCommand = "node dist/index.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
